server:
  port: 8084

spring:
  application:
    name: booking-service

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  datasource:
    url: jdbc:mysql://globalskill-globalskill.e.aivencloud.com:23246/booking-service?ssl-mode=REQUIRED
    username: avnadmin
    password: ${AIVEN_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: BookingServicePool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000         # 30 giây
      max-lifetime: 3300000       # 55 phút
      connection-timeout: 20000   # 20 giây
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true
